финальное задание 6го спринта
n00bertb/java-kanban pull request #2
Opened 2024-12-08 15:22 UTC by n00bertb

первая попытка сдать финальное задание 6го спринта

2024-12-09 16:24 UTC, mikita95 requested changes
Все отлично :) Оставил лишь небольшие замечания

2024-12-09 16:24 UTC, mikita95 commented on src/service/InMemoryTaskManager.java
> +    private int taskId = 0;
Поля лучше определять до конструктора по code style

2024-12-09 16:24 UTC, mikita95 commented on src/service/InMemoryTaskManager.java
> +    }
Нужно ещё и очищать историю при удалении по условию

2024-12-10 13:36 UTC, n00bertb commented
В задании если что ни слова про удаление из истории Эпиков и Сабтасок только про Таски... поэтому для них вышеописанное не делал, но если понадобится, то сделаю по аналогии.
Опять таки это выглядит разумным шагом/решением раз мы удаляем Таски то и их также должны -_-
Т.е. будем считать что я усвоил этот момент и если надо то добавлю его в любой момент времени.

2024-12-10 15:39 UTC, mikita95 approved these changes
Все отлично :) Можно мержить пул-реквест. Про удаление - стоит, конечно, удалять эпики и подзадачи тоже, если добавляем их в историю

2024-12-10 16:01 UTC, merged